# This file specifies your Python application's runtime configuration
# including URL routing, versions, static file uploads, etc. See
# https://developers.google.com/appengine/docs/python/config/appconfig
# for details.

# TODO: Enter your application id below. If you have signed up
# using cloud.google.com/console use the "project id" for your application
# id.
runtime: python27
api_version: 1
threadsafe: true
service: zorya-backend

builtins:
- deferred: on


# Handlers define how to route requests to your application.
handlers:
# Third party libraries that are included in the App Engine SDK must be listed

#- url: /api/v1/.*
 # script: main.app
 # login: optional
 # secure: always


# App Engine serves and caches static files contained in the listed directories
# (and subdirectories). Uncomment and set the directory as needed.
#- url: /client
#  static_dir: client

# This handler tells app engine how to route requests to a WSGI application.
# The script value is in the format <path.to.module>.<wsgi_application>
# where <wsgi_application> is a WSGI application object.
- url: .*  # This regex directs all routes to main.app
  script: main.app



# here if you want to use them.  See
# https://developers.google.com/appengine/docs/python/tools/libraries27 for
# a list of libraries included in the SDK.  Third party libs that are *not* part
# of the App Engine SDK don't need to be listed here, instead add them to your
# project directory, either as a git submodule or as a plain subdirectory.
#libraries:
#- name: jinja2
#  version: latest

libraries:
- name: ssl
  version: latest
- name: numpy
  version: "1.6.1"
